# Generated by Django 4.2 on 2025-11-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, default='https://picsum.photos/id/64/200/200', max_length=500, verbose_name='头像')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '保密')], max_length=10, verbose_name='性别')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='阅读兴趣')),
                ('is_vip', models.BooleanField(default=False, verbose_name='是否VIP')),
                ('vip_expire_date', models.DateField(blank=True, null=True, verbose_name='VIP到期日期')),
                ('member_since', models.DateField(auto_now_add=True, verbose_name='加入日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
